name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-jvm:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ 'Lab1J', 'Lab2J', 'Lab3J', 'Lab4J' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Build with Gradle
        run: ./gradlew :app${{matrix.version}}:build
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact-${{matrix.version}}
          path: ./app${{matrix.version}}/build/libs/*.jar
  build-native:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ 'Lab1N', 'Lab2N', 'Lab3N' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Build with Gradle
        run: ./gradlew :app${{matrix.version}}:build
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact-${{matrix.version}}
          path: ./app${{matrix.version}}/build/bin/mingwX64/releaseExecutable/*.exe
  build-gpu:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ 'Lab5-1J', 'Lab5-2J', 'Lab5-3J', 'Lab5-4J' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Build with Gradle
        run: ./gradlew :app${{matrix.version}}:build
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact-${{matrix.version}}
          path: ./app${{matrix.version}}/build/libs/*.jar
  merge:
    runs-on: windows-latest
    needs: [ build-jvm, build-native, build-gpu ]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@main
        with:
          name: compiled-artifact
          delete-merged: true